//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub mod prelude;

pub mod event;
pub mod oidc_provider;
pub mod source;
pub mod submission;
pub mod token;
pub mod user;
pub mod user_event;
pub mod vote;
