//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::event::Entity as Event;
pub use super::oidc_provider::Entity as OidcProvider;
pub use super::source::Entity as Source;
pub use super::submission::Entity as Submission;
pub use super::token::Entity as Token;
pub use super::user::Entity as User;
pub use super::user_event::Entity as UserEvent;
pub use super::vote::Entity as Vote;
